import type { ReactNode } from "react";
import { PrintActions } from "./PrintActions";

type Orientation = "portrait" | "landscape";

interface Props {
  orientation?: Orientation;
  backHref: string;
  backLabel?: string;
  children: ReactNode;
}

export function PrintShell({ orientation = "portrait", backHref, backLabel, children }: Props) {
  const orientationClass =
    orientation === "landscape" ? "print-shell-landscape" : "print-shell-portrait";
  const widthClass =
    orientation === "landscape"
      ? "max-w-[1400px] mx-auto print:max-w-none"
      : "max-w-[800px] mx-auto print:max-w-none";

  return (
    <div className={`${widthClass} ${orientationClass}`}>
      <PrintActions backHref={backHref} backLabel={backLabel} />
      {children}
    </div>
  );
}

interface HeaderProps {
  title: string;
  subtitle?: string;
  rightSlot?: ReactNode;
  /** Sub-line under the title, e.g. coach name & organization. */
  byline?: ReactNode;
}

export function PrintHeader({ title, subtitle, byline, rightSlot }: HeaderProps) {
  return (
    <div className="mb-6 pb-4 border-b-2 border-black dark:border-white print:border-black">
      <div className="flex items-baseline justify-between gap-4">
        <h1 className="text-xl font-heading font-bold print:text-black">{title}</h1>
        {rightSlot && (
          <div className="text-sm font-mono tabular-nums print:text-black">{rightSlot}</div>
        )}
      </div>
      {(byline || subtitle) && (
        <div className="flex items-baseline justify-between gap-4 mt-1">
          {byline && <p className="text-sm print:text-black">{byline}</p>}
          {subtitle && <p className="text-xs text-muted print:text-gray-600 ml-auto">{subtitle}</p>}
        </div>
      )}
    </div>
  );
}

export function PrintFooter() {
  return (
    <p className="mt-6 text-[10px] text-muted text-center print:text-gray-400">
      Generated by Podium Throws
    </p>
  );
}

/** Format a date for the print-date header line. */
export function formatPrintDate(d: Date = new Date()): string {
  return d.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}
